/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.packet.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * IPReservationRequestInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-12-14T20:42:56.777Z")
public class IPReservationRequestInput {
  @SerializedName("type")
  private String type = null;

  @SerializedName("quantity")
  private Integer quantity = null;

  @SerializedName("comments")
  private String comments = null;

  @SerializedName("facility")
  private String facility = null;

  @SerializedName("metro")
  private String metro = null;

  @SerializedName("customdata")
  private Object customdata = null;

  @SerializedName("tags")
  private List<String> tags = null;

  @SerializedName("details")
  private String details = null;

  @SerializedName("fail_on_approval_required")
  private Boolean failOnApprovalRequired = null;

  public IPReservationRequestInput type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public IPReservationRequestInput quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public IPReservationRequestInput comments(String comments) {
    this.comments = comments;
    return this;
  }

   /**
   * Get comments
   * @return comments
  **/
  @ApiModelProperty(value = "")
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public IPReservationRequestInput facility(String facility) {
    this.facility = facility;
    return this;
  }

   /**
   * Get facility
   * @return facility
  **/
  @ApiModelProperty(value = "")
  public String getFacility() {
    return facility;
  }

  public void setFacility(String facility) {
    this.facility = facility;
  }

  public IPReservationRequestInput metro(String metro) {
    this.metro = metro;
    return this;
  }

   /**
   * The code of the metro you are requesting the IP reservation in.
   * @return metro
  **/
  @ApiModelProperty(example = "SV", value = "The code of the metro you are requesting the IP reservation in.")
  public String getMetro() {
    return metro;
  }

  public void setMetro(String metro) {
    this.metro = metro;
  }

  public IPReservationRequestInput customdata(Object customdata) {
    this.customdata = customdata;
    return this;
  }

   /**
   * Get customdata
   * @return customdata
  **/
  @ApiModelProperty(value = "")
  public Object getCustomdata() {
    return customdata;
  }

  public void setCustomdata(Object customdata) {
    this.customdata = customdata;
  }

  public IPReservationRequestInput tags(List<String> tags) {
    this.tags = tags;
    return this;
  }

  public IPReservationRequestInput addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public List<String> getTags() {
    return tags;
  }

  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  public IPReservationRequestInput details(String details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @ApiModelProperty(value = "")
  public String getDetails() {
    return details;
  }

  public void setDetails(String details) {
    this.details = details;
  }

  public IPReservationRequestInput failOnApprovalRequired(Boolean failOnApprovalRequired) {
    this.failOnApprovalRequired = failOnApprovalRequired;
    return this;
  }

   /**
   * Get failOnApprovalRequired
   * @return failOnApprovalRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isFailOnApprovalRequired() {
    return failOnApprovalRequired;
  }

  public void setFailOnApprovalRequired(Boolean failOnApprovalRequired) {
    this.failOnApprovalRequired = failOnApprovalRequired;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IPReservationRequestInput ipReservationRequestInput = (IPReservationRequestInput) o;
    return Objects.equals(this.type, ipReservationRequestInput.type) &&
        Objects.equals(this.quantity, ipReservationRequestInput.quantity) &&
        Objects.equals(this.comments, ipReservationRequestInput.comments) &&
        Objects.equals(this.facility, ipReservationRequestInput.facility) &&
        Objects.equals(this.metro, ipReservationRequestInput.metro) &&
        Objects.equals(this.customdata, ipReservationRequestInput.customdata) &&
        Objects.equals(this.tags, ipReservationRequestInput.tags) &&
        Objects.equals(this.details, ipReservationRequestInput.details) &&
        Objects.equals(this.failOnApprovalRequired, ipReservationRequestInput.failOnApprovalRequired);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, quantity, comments, facility, metro, customdata, tags, details, failOnApprovalRequired);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IPReservationRequestInput {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    facility: ").append(toIndentedString(facility)).append("\n");
    sb.append("    metro: ").append(toIndentedString(metro)).append("\n");
    sb.append("    customdata: ").append(toIndentedString(customdata)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    failOnApprovalRequired: ").append(toIndentedString(failOnApprovalRequired)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

