/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.model;

import com.equinix.openapi.metal.v1.model.CapacityLevelPerBaremetal;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CapacityPerFacility
 */
public class CapacityPerFacilityTest {
    private final CapacityPerFacility model = new CapacityPerFacility();

    /**
     * Model tests for CapacityPerFacility
     */
    @Test
    public void testCapacityPerFacility() {
        // TODO: test CapacityPerFacility
    }

    /**
     * Test the property 'baremetal0'
     */
    @Test
    public void baremetal0Test() {
        // TODO: test baremetal0
    }

    /**
     * Test the property 'baremetal1'
     */
    @Test
    public void baremetal1Test() {
        // TODO: test baremetal1
    }

    /**
     * Test the property 'baremetal2'
     */
    @Test
    public void baremetal2Test() {
        // TODO: test baremetal2
    }

    /**
     * Test the property 'baremetal2a'
     */
    @Test
    public void baremetal2aTest() {
        // TODO: test baremetal2a
    }

    /**
     * Test the property 'baremetal2a2'
     */
    @Test
    public void baremetal2a2Test() {
        // TODO: test baremetal2a2
    }

    /**
     * Test the property 'baremetal3'
     */
    @Test
    public void baremetal3Test() {
        // TODO: test baremetal3
    }

    /**
     * Test the property 'baremetalS'
     */
    @Test
    public void baremetalSTest() {
        // TODO: test baremetalS
    }

    /**
     * Test the property 'c2MediumX86'
     */
    @Test
    public void c2MediumX86Test() {
        // TODO: test c2MediumX86
    }

    /**
     * Test the property 'm2XlargeX86'
     */
    @Test
    public void m2XlargeX86Test() {
        // TODO: test m2XlargeX86
    }

}
