/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.model;

import com.equinix.openapi.metal.v1.model.CapacityPerFacility;
import com.equinix.openapi.metal.v1.model.CapacityPerNewFacility;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CapacityReport
 */
public class CapacityReportTest {
    private final CapacityReport model = new CapacityReport();

    /**
     * Model tests for CapacityReport
     */
    @Test
    public void testCapacityReport() {
        // TODO: test CapacityReport
    }

    /**
     * Test the property 'ams1'
     */
    @Test
    public void ams1Test() {
        // TODO: test ams1
    }

    /**
     * Test the property 'atl1'
     */
    @Test
    public void atl1Test() {
        // TODO: test atl1
    }

    /**
     * Test the property 'dfw1'
     */
    @Test
    public void dfw1Test() {
        // TODO: test dfw1
    }

    /**
     * Test the property 'ewr1'
     */
    @Test
    public void ewr1Test() {
        // TODO: test ewr1
    }

    /**
     * Test the property 'fra1'
     */
    @Test
    public void fra1Test() {
        // TODO: test fra1
    }

    /**
     * Test the property 'iad1'
     */
    @Test
    public void iad1Test() {
        // TODO: test iad1
    }

    /**
     * Test the property 'lax1'
     */
    @Test
    public void lax1Test() {
        // TODO: test lax1
    }

    /**
     * Test the property 'nrt1'
     */
    @Test
    public void nrt1Test() {
        // TODO: test nrt1
    }

    /**
     * Test the property 'ord1'
     */
    @Test
    public void ord1Test() {
        // TODO: test ord1
    }

    /**
     * Test the property 'sea1'
     */
    @Test
    public void sea1Test() {
        // TODO: test sea1
    }

    /**
     * Test the property 'sin1'
     */
    @Test
    public void sin1Test() {
        // TODO: test sin1
    }

    /**
     * Test the property 'sjc1'
     */
    @Test
    public void sjc1Test() {
        // TODO: test sjc1
    }

    /**
     * Test the property 'syd1'
     */
    @Test
    public void syd1Test() {
        // TODO: test syd1
    }

    /**
     * Test the property 'yyz1'
     */
    @Test
    public void yyz1Test() {
        // TODO: test yyz1
    }

}
