/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OperatingSystem
 */
public class OperatingSystemTest {
    private final OperatingSystem model = new OperatingSystem();

    /**
     * Model tests for OperatingSystem
     */
    @Test
    public void testOperatingSystem() {
        // TODO: test OperatingSystem
    }

    /**
     * Test the property 'distro'
     */
    @Test
    public void distroTest() {
        // TODO: test distro
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'licensed'
     */
    @Test
    public void licensedTest() {
        // TODO: test licensed
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'preinstallable'
     */
    @Test
    public void preinstallableTest() {
        // TODO: test preinstallable
    }

    /**
     * Test the property 'pricing'
     */
    @Test
    public void pricingTest() {
        // TODO: test pricing
    }

    /**
     * Test the property 'provisionableOn'
     */
    @Test
    public void provisionableOnTest() {
        // TODO: test provisionableOn
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
