/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.model;

import com.equinix.openapi.metal.v1.model.Href;
import com.equinix.openapi.metal.v1.model.PlanAvailableInMetrosInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Plan
 */
public class PlanTest {
    private final Plan model = new Plan();

    /**
     * Model tests for Plan
     */
    @Test
    public void testPlan() {
        // TODO: test Plan
    }

    /**
     * Test the property 'availableIn'
     */
    @Test
    public void availableInTest() {
        // TODO: test availableIn
    }

    /**
     * Test the property 'deploymentTypes'
     */
    @Test
    public void deploymentTypesTest() {
        // TODO: test deploymentTypes
    }

    /**
     * Test the property 'availableInMetros'
     */
    @Test
    public void availableInMetrosTest() {
        // TODO: test availableInMetros
    }

    /**
     * Test the property 'propertyClass'
     */
    @Test
    public void propertyClassTest() {
        // TODO: test propertyClass
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'legacy'
     */
    @Test
    public void legacyTest() {
        // TODO: test legacy
    }

    /**
     * Test the property 'line'
     */
    @Test
    public void lineTest() {
        // TODO: test line
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'pricing'
     */
    @Test
    public void pricingTest() {
        // TODO: test pricing
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'specs'
     */
    @Test
    public void specsTest() {
        // TODO: test specs
    }

}
