/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.api;

import com.equinix.openapi.metal.v1.model.InlineResponse20050;
import com.equinix.openapi.metal.v1.model.InlineResponse401;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OtPsApi
 */
@Ignore
public class OtPsApiTest {

    private final OtPsApi api = new OtPsApi();

    
    /**
     * Verify user by providing an OTP
     *
     * It verifies the user once a valid OTP is provided. It gives back a session token, essentially logging in the user.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findEnsureOtpTest() throws Exception {
        String otp = null;
        api.findEnsureOtp(otp);

        // TODO: test validations
    }
    
    /**
     * Retrieve my recovery codes
     *
     * Returns my recovery codes.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findRecoveryCodesTest() throws Exception {
        InlineResponse20050 response = api.findRecoveryCodes();

        // TODO: test validations
    }
    
    /**
     * Generate new recovery codes
     *
     * Generate a new set of recovery codes.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void regenerateCodesTest() throws Exception {
        InlineResponse20050 response = api.regenerateCodes();

        // TODO: test validations
    }
    
}
