/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.api;

import com.equinix.openapi.metal.v1.model.Body17;
import com.equinix.openapi.metal.v1.model.InlineResponse20028PaymentMethods;
import com.equinix.openapi.metal.v1.model.InlineResponse401;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentMethodsApi
 */
@Ignore
public class PaymentMethodsApiTest {

    private final PaymentMethodsApi api = new PaymentMethodsApi();

    
    /**
     * Delete the payment method
     *
     * Deletes the payment method.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deletePaymentMethodTest() throws Exception {
        UUID id = null;
        api.deletePaymentMethod(id);

        // TODO: test validations
    }
    
    /**
     * Retrieve a payment method
     *
     * Returns a payment method
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findPaymentMethodByIdTest() throws Exception {
        UUID id = null;
        List<String> include = null;
        List<String> exclude = null;
        InlineResponse20028PaymentMethods response = api.findPaymentMethodById(id, include, exclude);

        // TODO: test validations
    }
    
    /**
     * Update the payment method
     *
     * Updates the payment method.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updatePaymentMethodTest() throws Exception {
        UUID id = null;
        Body17 body = null;
        InlineResponse20028PaymentMethods response = api.updatePaymentMethod(id, body);

        // TODO: test validations
    }
    
}
