/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.api;

import com.equinix.openapi.ApiException;
import com.equinix.openapi.metal.v1.model.Error;
import com.equinix.openapi.metal.v1.model.PlanList;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlansApi
 */
@Disabled
public class PlansApiTest {

    private final PlansApi api = new PlansApi();

    /**
     * Retrieve all plans
     *
     * Provides a listing of available plans to provision your device on.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findPlansTest() throws ApiException {
        List<String> include = null;
        List<String> exclude = null;
        PlanList response = api.findPlans(include, exclude);
        // TODO: test validations
    }

    /**
     * Retrieve all plans visible by the project
     *
     * Returns a listing of available plans for the given project
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findPlansByProjectTest() throws ApiException {
        UUID id = null;
        List<String> include = null;
        List<String> exclude = null;
        PlanList response = api.findPlansByProject(id, include, exclude);
        // TODO: test validations
    }

}
