/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.equinix.openapi.metal.v1.model.InlineResponse2001;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BgpSessionList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-20T13:48:24.543Z")
public class BgpSessionList {
  @SerializedName("bgp_sessions")
  private List<InlineResponse2001> bgpSessions = null;

  public BgpSessionList bgpSessions(List<InlineResponse2001> bgpSessions) {
    this.bgpSessions = bgpSessions;
    return this;
  }

  public BgpSessionList addBgpSessionsItem(InlineResponse2001 bgpSessionsItem) {
    if (this.bgpSessions == null) {
      this.bgpSessions = new ArrayList<InlineResponse2001>();
    }
    this.bgpSessions.add(bgpSessionsItem);
    return this;
  }

   /**
   * Get bgpSessions
   * @return bgpSessions
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2001> getBgpSessions() {
    return bgpSessions;
  }

  public void setBgpSessions(List<InlineResponse2001> bgpSessions) {
    this.bgpSessions = bgpSessions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BgpSessionList bgpSessionList = (BgpSessionList) o;
    return Objects.equals(this.bgpSessions, bgpSessionList.bgpSessions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bgpSessions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BgpSessionList {\n");
    
    sb.append("    bgpSessions: ").append(toIndentedString(bgpSessions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

