/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.equinix.openapi.metal.v1.model.InlineResponse20012Meta;
import com.equinix.openapi.metal.v1.model.InlineResponse2011;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * HardwareReservationList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-20T13:48:24.543Z")
public class HardwareReservationList {
  @SerializedName("hardware_reservations")
  private List<InlineResponse2011> hardwareReservations = null;

  @SerializedName("meta")
  private InlineResponse20012Meta meta = null;

  public HardwareReservationList hardwareReservations(List<InlineResponse2011> hardwareReservations) {
    this.hardwareReservations = hardwareReservations;
    return this;
  }

  public HardwareReservationList addHardwareReservationsItem(InlineResponse2011 hardwareReservationsItem) {
    if (this.hardwareReservations == null) {
      this.hardwareReservations = new ArrayList<InlineResponse2011>();
    }
    this.hardwareReservations.add(hardwareReservationsItem);
    return this;
  }

   /**
   * Get hardwareReservations
   * @return hardwareReservations
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2011> getHardwareReservations() {
    return hardwareReservations;
  }

  public void setHardwareReservations(List<InlineResponse2011> hardwareReservations) {
    this.hardwareReservations = hardwareReservations;
  }

  public HardwareReservationList meta(InlineResponse20012Meta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @ApiModelProperty(value = "")
  public InlineResponse20012Meta getMeta() {
    return meta;
  }

  public void setMeta(InlineResponse20012Meta meta) {
    this.meta = meta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HardwareReservationList hardwareReservationList = (HardwareReservationList) o;
    return Objects.equals(this.hardwareReservations, hardwareReservationList.hardwareReservations) &&
        Objects.equals(this.meta, hardwareReservationList.meta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hardwareReservations, meta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HardwareReservationList {\n");
    
    sb.append("    hardwareReservations: ").append(toIndentedString(hardwareReservations)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

