/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineResponse20010RoutesIn
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-20T13:48:24.543Z")
public class InlineResponse20010RoutesIn {
  @SerializedName("exact")
  private Boolean exact = null;

  @SerializedName("route")
  private String route = null;

  public InlineResponse20010RoutesIn exact(Boolean exact) {
    this.exact = exact;
    return this;
  }

   /**
   * Get exact
   * @return exact
  **/
  @ApiModelProperty(value = "")
  public Boolean isExact() {
    return exact;
  }

  public void setExact(Boolean exact) {
    this.exact = exact;
  }

  public InlineResponse20010RoutesIn route(String route) {
    this.route = route;
    return this;
  }

   /**
   * A project network
   * @return route
  **/
  @ApiModelProperty(example = "10.32.16.0/31", value = "A project network")
  public String getRoute() {
    return route;
  }

  public void setRoute(String route) {
    this.route = route;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20010RoutesIn inlineResponse20010RoutesIn = (InlineResponse20010RoutesIn) o;
    return Objects.equals(this.exact, inlineResponse20010RoutesIn.exact) &&
        Objects.equals(this.route, inlineResponse20010RoutesIn.route);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exact, route);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20010RoutesIn {\n");
    
    sb.append("    exact: ").append(toIndentedString(exact)).append("\n");
    sb.append("    route: ").append(toIndentedString(route)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

