/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.equinix.openapi.metal.v1.model.InlineResponse20043SpotMarketRequests;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse20043
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-20T13:48:24.543Z")
public class InlineResponse20043 {
  @SerializedName("spot_market_requests")
  private List<InlineResponse20043SpotMarketRequests> spotMarketRequests = null;

  public InlineResponse20043 spotMarketRequests(List<InlineResponse20043SpotMarketRequests> spotMarketRequests) {
    this.spotMarketRequests = spotMarketRequests;
    return this;
  }

  public InlineResponse20043 addSpotMarketRequestsItem(InlineResponse20043SpotMarketRequests spotMarketRequestsItem) {
    if (this.spotMarketRequests == null) {
      this.spotMarketRequests = new ArrayList<InlineResponse20043SpotMarketRequests>();
    }
    this.spotMarketRequests.add(spotMarketRequestsItem);
    return this;
  }

   /**
   * Get spotMarketRequests
   * @return spotMarketRequests
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse20043SpotMarketRequests> getSpotMarketRequests() {
    return spotMarketRequests;
  }

  public void setSpotMarketRequests(List<InlineResponse20043SpotMarketRequests> spotMarketRequests) {
    this.spotMarketRequests = spotMarketRequests;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20043 inlineResponse20043 = (InlineResponse20043) o;
    return Objects.equals(this.spotMarketRequests, inlineResponse20043.spotMarketRequests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(spotMarketRequests);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20043 {\n");
    
    sb.append("    spotMarketRequests: ").append(toIndentedString(spotMarketRequests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

