/*
 * Metal API
 * This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@equinixmetal.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.equinix.openapi.metal.v1.model;

import java.util.Objects;
import java.util.Arrays;
import com.equinix.openapi.metal.v1.model.InlineResponse200Devices;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Plan
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-07-20T13:48:24.543Z")
public class Plan {
  @SerializedName("available_in")
  private List<InlineResponse200Devices> availableIn = null;

  @SerializedName("class")
  private String propertyClass = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("legacy")
  private Boolean legacy = null;

  @SerializedName("line")
  private String line = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("pricing")
  private Object pricing = null;

  @SerializedName("slug")
  private String slug = null;

  @SerializedName("specs")
  private Object specs = null;

  public Plan availableIn(List<InlineResponse200Devices> availableIn) {
    this.availableIn = availableIn;
    return this;
  }

  public Plan addAvailableInItem(InlineResponse200Devices availableInItem) {
    if (this.availableIn == null) {
      this.availableIn = new ArrayList<InlineResponse200Devices>();
    }
    this.availableIn.add(availableInItem);
    return this;
  }

   /**
   * Shows which facilities the plan is available in, and the facility-based price if it is different from the default price.
   * @return availableIn
  **/
  @ApiModelProperty(value = "Shows which facilities the plan is available in, and the facility-based price if it is different from the default price.")
  public List<InlineResponse200Devices> getAvailableIn() {
    return availableIn;
  }

  public void setAvailableIn(List<InlineResponse200Devices> availableIn) {
    this.availableIn = availableIn;
  }

  public Plan propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * Get propertyClass
   * @return propertyClass
  **/
  @ApiModelProperty(value = "")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }

  public Plan description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Plan id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public Plan legacy(Boolean legacy) {
    this.legacy = legacy;
    return this;
  }

   /**
   * Get legacy
   * @return legacy
  **/
  @ApiModelProperty(value = "")
  public Boolean isLegacy() {
    return legacy;
  }

  public void setLegacy(Boolean legacy) {
    this.legacy = legacy;
  }

  public Plan line(String line) {
    this.line = line;
    return this;
  }

   /**
   * Get line
   * @return line
  **/
  @ApiModelProperty(value = "")
  public String getLine() {
    return line;
  }

  public void setLine(String line) {
    this.line = line;
  }

  public Plan name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Plan pricing(Object pricing) {
    this.pricing = pricing;
    return this;
  }

   /**
   * Get pricing
   * @return pricing
  **/
  @ApiModelProperty(value = "")
  public Object getPricing() {
    return pricing;
  }

  public void setPricing(Object pricing) {
    this.pricing = pricing;
  }

  public Plan slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Get slug
   * @return slug
  **/
  @ApiModelProperty(value = "")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public Plan specs(Object specs) {
    this.specs = specs;
    return this;
  }

   /**
   * Get specs
   * @return specs
  **/
  @ApiModelProperty(value = "")
  public Object getSpecs() {
    return specs;
  }

  public void setSpecs(Object specs) {
    this.specs = specs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Plan plan = (Plan) o;
    return Objects.equals(this.availableIn, plan.availableIn) &&
        Objects.equals(this.propertyClass, plan.propertyClass) &&
        Objects.equals(this.description, plan.description) &&
        Objects.equals(this.id, plan.id) &&
        Objects.equals(this.legacy, plan.legacy) &&
        Objects.equals(this.line, plan.line) &&
        Objects.equals(this.name, plan.name) &&
        Objects.equals(this.pricing, plan.pricing) &&
        Objects.equals(this.slug, plan.slug) &&
        Objects.equals(this.specs, plan.specs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availableIn, propertyClass, description, id, legacy, line, name, pricing, slug, specs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Plan {\n");
    
    sb.append("    availableIn: ").append(toIndentedString(availableIn)).append("\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    legacy: ").append(toIndentedString(legacy)).append("\n");
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pricing: ").append(toIndentedString(pricing)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    specs: ").append(toIndentedString(specs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

