# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Execute functional tests for device related workflows

on:
  workflow_call:
    secrets:
      token:
        description: 'API token key for tests'
        required: true
      project_uuid:
        description: 'UUID of project to perform tests'
        required: true

  workflow_dispatch:
    inputs:
        metro:
          description: 'metro code where you want to deploy the instance'
          default: 'DA'
          required: true
        os:
          description: 'operating system slug'
          default: 'debian_11'
          required: true
        plan:
          description: 'instance server plan'
          default: 'c3.small.x86'
          required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Run equinix metal-java make
      run: make generate

    - name: Install equinix client
      working-directory: ./equinix-openapi-metal
      run: mvn clean install --file pom.xml

    - name: Set env parameters amd create device-test props file
      run: |
        echo "metro=${{ github.event.inputs.metro }}" > equinix-functional-test/src/test/resources/device-test.properties
        echo -e "\nos=${{ github.event.inputs.os }}" >> equinix-functional-test/src/test/resources/device-test.properties
        echo -e "\nplan=${{ github.event.inputs.plan }}" >> equinix-functional-test/src/test/resources/device-test.properties

        echo `cat equinix-functional-test/src/test/resources/device-test.properties`

    - name: Run functional tests for DeviceOperator.
      working-directory: ./equinix-functional-test
      run: mvn clean test -Dtest=com.equinix.test.functional.TestDeviceOperator.java --file pom.xml
      env:
        FUNCTIONAL_TEST_TOKEN: ${{ secrets.token }}
        FUNCTIONAL_TEST_PROJECT_UUID: ${{ secrets.project_uuid }}
